### ISSUE TITLE
Unable to set a reminder when importing a calendar from URL

### ISSUE THREAD

**Issue by flonkler** [LeEnno/htwk2ical#5]
## Short description

It'd like to add a reminder for lectures. Unfortunately, if I import an ICAL into my Outlook, I am unable to edit an appointment. Is it possible to permit those changes?

It seems like the calender is write-protected. However, if I were able to change options of an appointment, will others that import the ICAL have the same option? 

## Steps to reproduce

1. Choose an arbitrary course, I chose "18TIB-2 – Telekommunikationsinformatik Bachelor"
2. Create the calendar
3. Import the calendar in Outlook using the given URL, e.g. http://www.htwk-stundenplan.de/8e20719a/
4. Find an appointment item and edit the reminder option
5. Save the appointment
6. **Warning appears, unable change the appointment item**

## Expected result

The reminder options can be changed to, say "15 minutes", and I will be reminded 15 minutes before the lecture / online classroom begins.

## Actual result

When I try to save, it tells me that the folder is write-protected. The reminder option is always "no reminder".

**Comment by LeEnno** [comment]
After creating a calendar you have 2 options: download the calendar or subscribe via an URL. The first one has the advantage of being editable but does not update itself in case of lecture changes. The second one *does* reflect lecture changes but you can’t edit it. Due to the nature of those different approaches – local vs remote persistence – it’s not possible to persist reminders when using the subscribe option. 

There may be clients who are able to set local reminders for remote events. But you probably don’t want to change your calendar client just to gain that ability.

If you really need the reminders I would suggest sticking with the download option.

Oooooooor you could get really fancy and do both – download and subscribe. Use the downloaded one for reminders and the subscribed one for staying on top of changes. Maybe you can hide the downloaded one from the view but still fire reminders? I don’t know how Outlook works and this is a pretty weird hack. But I can’t think of a better solution.

**Comment by flonkler** [comment]
I see.
What requirements do I have, if I want to have a (private) synchronized schedule that I can modify myself? Could you explain how htwk2ical works internally or how it updates the calendars?

**Comment by LeEnno** [comment]
Remote syncing and local modifying unfortunately don’t go together in this situation.

Updating calendars works by scraping contents from HTWK‘s site regularly. Those contents will be transformed and stored in the database. When a calendar is requested it reads the relevant pieces from the database and returns an `.ics` file.

Hope this helps.

**Comment by flonkler** [comment]
Thanks for the information :+1:
I'll close the issue.
